#!/bin/sh
#///////////////////////////////////////////////////////////////////////////////
#// 
#// $URL$
#//
#///////////////////////////////////////////////////////////////////////////////
#// Revision  : $LastChangedRevision$
#// Project   : MRROC++
#///////////////////////////////////////////////////////////////////////////////
#// Created   : 2007-01-12
#// Developer : tkornuta
#// Modified  : $LastChangedDate$
#// By        : $LastChangedBy$
#///////////////////////////////////////////////////////////////////////////////
#// File description:
#// 
#//   Script for indenting the files with the indent program.
#// 
#///////////////////////////////////////////////////////////////////////////////


#-----KODY BLEDOW-------------
Err_OK=0
Err_NO_FILE=1
Err_EMPTY_FILE=2

#-----------------------------
MASK="*.h *.hpp *.cc *.cpp"

#-----OPCJE INDENTA-----------
BLANK_LINES="--blank-lines-after-declarations \
                --blank-lines-after-procedures \
                --leave-optional-blank-lines"

BREAKING_LONG_LINES=""

DECLARATIONS="--blank-lines-after-commas \
                --break-function-decl-args \
                --braces-after-struct-decl-line \
                --declaration-indentation1 \
                --dont-break-procedure-type"

STATEMENTS="--no-space-after-function-call-names \
                --no-space-after-parentheses" 

COMMENTS="--dont-format-comments"

INDENTATIONS=""

MISC="--verbose"

COMMON_STYLES=""

INVOKING_INDENT=""

#-----------------------------------------------------
do_the_indent ()
{

  if [ -z "$1" ]; then
  {
    print - u2 "jindent::do_the_jindent : nie podano nazwy pliku" 
    exit 1
  }
  fi 
  
  if [ -z "$2" ]; then
  {
    PLIKI="$1" #indent stworzy plik backupowy *.~ indentowanego pliku
  }
  else
  {
    PLIKI="$1 -o $2"
  }
  fi 
  
  print "indenting files: $PLIKI"
  indent $BLANK_LINES \
        $BREAKING_LONG_LINES \
        $DECLARATIONS \
        $STATEMENTS \
        $COMMENTS \
        $INDENTATIONS \
        $MISC \
        $COMMON_STYLES \
        $INVOKING_INDENT $PLIKI

}
#-----------------------------------------------------


# jesli nie podano pliku do potraktowania indentem to pojdzie w petli po plikach z katalogu:
if [ -z "$1" ]; then
{
  for PLIK in $MASK 
    do
      {
      do_the_indent $PLIK
      }
    done 
  exit 0
  }
else
{
  SOURCE=$1
}
fi

# jesli nie podano pliku wynikowego to zachowa sie defaultowo czyli zapisze pod nazwa zrodla, 
# ale zrobi backup pliku w postaci <nazwa_pliku>.<rozszerzenie>~:
if [ -z "$2" ]; then
{
  DESTINATION=""
}
else
{
  DESTINATION=$2
}
fi

# przepuszczenie pojedynczego pliku przez indenta z podanymi parametrami:
echo Pliki: $SOURCE $DESTINATION
do_the_indent $SOURCE $DESTINATION

#-----------------------------------------------------

