/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* arg count for dma capture function */
/* #undef DC1394_DMA_SETUP_CAPTURE_ARGS */

/* disable 500Kbps comms with SICK */
/* #undef DISABLE_HIGHSPEEDSICK */

/* Define to 1 if you have the `alphasort' function. */
#define HAVE_ALPHASORT 1

/* Define to 1 if you have the `cfmakeraw' function. */
#define HAVE_CFMAKERAW 1

/* Define to 1 if you have the `dirname' function. */
#define HAVE_DIRNAME 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the `getaddrinfo' function. */
/* #undef HAVE_GETADDRINFO */

/* gz_client_wait is defined */
/* #undef HAVE_GZ_CLIENT_WAIT */

/* gz_fiducial_fid_t.pose is defined */
/* #undef HAVE_GZ_FID_POSE */

/* gz_gps_data_t.utc_time is defined */
/* #undef HAVE_GZ_GPS_UTC */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <jpeglib.h> header file. */
/* #undef HAVE_JPEGLIB_H */

/* Define to 1 if you have the `crypto' library (-lcrypto). */
/* #undef HAVE_LIBCRYPTO */

/* Define to 1 if you have the jpeg library (-ljpeg). */
/* #undef HAVE_LIBJPEG */

/* Define to 1 if you have the ltdl library (-lltdl). */
/* #undef HAVE_LIBLTDL */

/* Define to 1 if you have the `nsl' library (-lnsl). */
/* #undef HAVE_LIBNSL */

/* Define to 1 if you have the `rt' library (-lrt). */
/* #undef HAVE_LIBRT */

/* Define to 1 if you have the `socket' library (-lsocket). */
#define HAVE_LIBSOCKET 1

/* Define to 1 if you have the <linux/joystick.h> header file. */
/* #undef HAVE_LINUX_JOYSTICK_H */

/* Define to 1 if you have the <linux/serial.h> header file. */
/* #undef HAVE_LINUX_SERIAL_H */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* OpenCV library is present */
/* #define HAVE_OPENCV 1 */

/* Define to 1 if you have the <openssl/md5.h> header file. */
/* #undef HAVE_OPENSSL_MD5_H */

/* Define to 1 if you have the `poll' function. */
#define HAVE_POLL 1

/* Define to 1 if you have the `scandir' function. */
#define HAVE_SCANDIR 1

/* Define to 1 if you have the `sigblock' function. */
#define HAVE_SIGBLOCK 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/filio.h> header file. */
/* #undef HAVE_SYS_FILIO_H */

/* Define to 1 if you have the <sys/soundcard.h> header file. */
/* #undef HAVE_SYS_SOUNDCARD_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* include the acoustics driver */
/* #undef INCLUDE_ACOUSTICS */

/* include the acts driver */
/* #undef INCLUDE_ACTS */

/* [include], [the], [AMCL], [driver] */
/* #undef INCLUDE_AMCL */

/* include the amtecpowercube driver */
/* #undef INCLUDE_AMTECPOWERCUBE */

/* include the aodv driver */
/* #undef INCLUDE_AODV */

/* include the bumpersafe driver */
/* #undef INCLUDE_BUMPERSAFE */

/* include the camera1394 driver */
/* #undef INCLUDE_CAMERA1394 */

/* include the cameracompress driver */
/* #undef INCLUDE_CAMERACOMPRESS */

/* include the camerav4l driver */
/* #undef INCLUDE_CAMERAV4L */

/* include the canonvcc4 driver */
/* #undef INCLUDE_CANONVCC4 */

/* include the clodbuster driver */
/* #undef INCLUDE_CLODBUSTER */

/* include the cmucam2 driver */
/* #undef INCLUDE_CMUCAM2 */

/* include the cmvision driver */
/* #undef INCLUDE_CMVISION */

/* include the dummy driver */
/* #undef INCLUDE_DUMMY */

/* include the er1 driver */
/* #undef INCLUDE_ER1 */

/* include the fakelocalize driver */
/* #undef INCLUDE_FAKELOCALIZE */

/* include the festival driver */
/* #undef INCLUDE_FESTIVAL */

/* include the fixedtones driver */
/* #undef INCLUDE_FIXEDTONES */

/* include the flockofbirds driver */
/* #undef INCLUDE_FLOCKOFBIRDS */

/* include the garminnmea driver */
/* #undef INCLUDE_GARMINNMEA */

/* include the driver */
/* #undef INCLUDE_GAZEBO */

/* include the gazebo camera driver */
/* #undef INCLUDE_GAZEBO_CAMERA */

/* include the gazebo factory driver */
/* #undef INCLUDE_GAZEBO_FACTORY */

/* include the gazebo fiducial driver */
/* #undef INCLUDE_GAZEBO_FIDUCIAL */

/* include the gazebo gps driver */
/* #undef INCLUDE_GAZEBO_GPS */

/* include the gazebo gripper driver */
/* #undef INCLUDE_GAZEBO_GRIPPER */

/* include the gazebo laser driver */
/* #undef INCLUDE_GAZEBO_LASER */

/* include the gazebo position driver */
/* #undef INCLUDE_GAZEBO_POSITION */

/* include the gazebo position3d driver */
/* #undef INCLUDE_GAZEBO_POSITION3D */

/* include the gazebo power driver */
/* #undef INCLUDE_GAZEBO_POWER */

/* include the gazebo ptz driver */
/* #undef INCLUDE_GAZEBO_PTZ */

/* include the gazebo sim driver */
/* #undef INCLUDE_GAZEBO_SIM */

/* include the gazebo sonar driver */
/* #undef INCLUDE_GAZEBO_SONAR */

/* include the gazebo sonars driver */
/* #undef INCLUDE_GAZEBO_SONARS */

/* include the gazebo stereo driver */
/* #undef INCLUDE_GAZEBO_STEREO */

/* include the gazebo truth driver */
/* #undef INCLUDE_GAZEBO_TRUTH */

/* include the imageseq driver */
/* #undef INCLUDE_IMAGESEQ */

/* include the isense driver */
/* #undef INCLUDE_ISENSE */

/* include the iwspy driver */
/* #undef INCLUDE_IWSPY */

/* include the khepera driver */
/* #undef INCLUDE_KHEPERA */

/* include the laserbar driver */
/* #undef INCLUDE_LASERBAR */

/* include the laserbarcode driver */
/* #undef INCLUDE_LASERBARCODE */

/* include the lasercspace driver */
/* #undef INCLUDE_LASERCSPACE */

/* include the laservisualbarcode driver */
/* #undef INCLUDE_LASERVISUALBARCODE */

/* include the laservisualbw driver */
/* #undef INCLUDE_LASERVISUALBW */

/* include the lifomcom driver */
/* #undef INCLUDE_LIFOMCOM */

/* include the linuxjoystick driver */
/* #undef INCLUDE_LINUXJOYSTICK */

/* include the linuxwifi driver */
/* #undef INCLUDE_LINUXWIFI */

/* include the logfile driver */
/* #undef INCLUDE_LOGFILE */

/* include the mapcspace driver */
/* #undef INCLUDE_MAPCSPACE */

/* include the mapfile driver */
/* #undef INCLUDE_MAPFILE */

/* include the mapscale driver */
/* #undef INCLUDE_MAPSCALE */

/* include the microstrain driver */
/* #undef INCLUDE_MICROSTRAIN */

/* include the mixer driver */
/* #undef INCLUDE_MIXER */

/* include the nomad driver */
/* #undef INCLUDE_NOMAD */

/* include the obot driver */
/* #undef INCLUDE_OBOT */

/* include the p2os driver */
/* #undef INCLUDE_P2OS */

/* include the passthrough driver */
/* #undef INCLUDE_PASSTHROUGH */

/* include the ptu46 driver */
/* #undef INCLUDE_PTU46 */

/* include the reb driver */
/* #undef INCLUDE_REB */

/* include the rflex driver */
/* #undef INCLUDE_RFLEX */

/* [include], [the], [RTK], [GUI], [in], [server], [(debugging)] */
/* #undef INCLUDE_RTKGUI */

/* include the rwi driver */
/* #undef INCLUDE_RWI */

/* include the segwayrmp driver */
/* #undef INCLUDE_SEGWAYRMP */

/* include the service_adv_lsd driver */
/* #undef INCLUDE_SERVICE_ADV_LSD */

/* include the service_adv_mdns driver */
/* #undef INCLUDE_SERVICE_ADV_MDNS */

/* include the sicklms200 driver */
/* #undef INCLUDE_SICKLMS200 */

/* include the sickpls driver */
/* #undef INCLUDE_SICKPLS */

/* include the simpleshape driver */
/* #undef INCLUDE_SIMPLESHAPE */

/* include the sonyevid30 driver */
/* #undef INCLUDE_SONYEVID30 */

/* include the sphinx2 driver */
/* #undef INCLUDE_SPHINX2 */

/* include the stage driver */
/* #undef INCLUDE_STAGE */

/* include the upcbarcode driver */
/* #undef INCLUDE_UPCBARCODE */

/* include the vfh driver */
/* #undef INCLUDE_VFH */

/* include the waveaudio driver */
/* #undef INCLUDE_WAVEAUDIO */

/* include the wavefront driver */
/* #undef INCLUDE_WAVEFRONT */

/* must define this on some non-Linux platforms */
/* #undef O_SYNC */

/* Name of package */
#define PACKAGE "player"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "player"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "player 1.6.5"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "player"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.6.5"

/* Thread Safe C++ Client Library */
#define PLAYERCLIENT_THREAD 1

/* allow big message packets (experimental) */
#define PLAYER_BIG_MESSAGES 1

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "1.6.5"

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef lib::WORDS_BIGENDIAN */

/* must define this on BSD-based platforms */
/* #undef socklen_t */
