#ifndef __SWARMITFIX_H
#define __SWARMITFIX_H

namespace mrrocpp {
namespace lib {

enum EPOS_GEN_PROFILE {
	TRAPEZOIDAL_VELOCITY, CUBIC_POSITION, EPOS_GEN_PROFILE_NO_ACTION
};

enum SMB_PIN_INSERTION {
	INSERT, WITHDRAWN, SMB_PIN_INSERTION_NO_ACTION
}; // namespace mrrocpp

enum SMB_PIN_LOCKING {
	CLAMB, UNCLAMB, SMB_PIN_LOCKING_NO_ACTION
}; // namespace mrrocpp

enum SHEAD_HEAD_SOLIDIFICATION {
	SOLIDIFY, DESOLIDIFY, SHEAD_HEAD_SOLIDIFICATION_NO_ACTION
}; // namespace mrrocpp

enum SHEAD_VACUUM_ACTIVATION {
	VACUUM_ON, VACUUM_OFF, SHEAD_VACUUM_ACTIVATION_NO_ACTION
}; // namespace mrrocpp

}
}

#endif
