// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ati3084.proto

#ifndef PROTOBUF_ati3084_2eproto__INCLUDED
#define PROTOBUF_ati3084_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/service.h>
#include "Common.pb.h"
// @@protoc_insertion_point(includes)

namespace mrrocpp {
namespace edp {
namespace sensor {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ati3084_2eproto();
void protobuf_AssignDesc_ati3084_2eproto();
void protobuf_ShutdownFile_ati3084_2eproto();

class GenForceReading;
class SendBiasRequest;
class SendBiasReply;

// ===================================================================

class GenForceReading : public ::google::protobuf::Message {
 public:
  GenForceReading();
  virtual ~GenForceReading();
  
  GenForceReading(const GenForceReading& from);
  
  inline GenForceReading& operator=(const GenForceReading& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const GenForceReading& default_instance();
  
  void Swap(GenForceReading* other);
  
  // implements Message ----------------------------------------------
  
  GenForceReading* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GenForceReading& from);
  void MergeFrom(const GenForceReading& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required sint32 fx = 1;
  inline bool has_fx() const;
  inline void clear_fx();
  static const int kFxFieldNumber = 1;
  inline ::google::protobuf::int32 fx() const;
  inline void set_fx(::google::protobuf::int32 value);
  
  // required sint32 fy = 2;
  inline bool has_fy() const;
  inline void clear_fy();
  static const int kFyFieldNumber = 2;
  inline ::google::protobuf::int32 fy() const;
  inline void set_fy(::google::protobuf::int32 value);
  
  // required sint32 fz = 3;
  inline bool has_fz() const;
  inline void clear_fz();
  static const int kFzFieldNumber = 3;
  inline ::google::protobuf::int32 fz() const;
  inline void set_fz(::google::protobuf::int32 value);
  
  // required sint32 tx = 4;
  inline bool has_tx() const;
  inline void clear_tx();
  static const int kTxFieldNumber = 4;
  inline ::google::protobuf::int32 tx() const;
  inline void set_tx(::google::protobuf::int32 value);
  
  // required sint32 ty = 5;
  inline bool has_ty() const;
  inline void clear_ty();
  static const int kTyFieldNumber = 5;
  inline ::google::protobuf::int32 ty() const;
  inline void set_ty(::google::protobuf::int32 value);
  
  // required sint32 tz = 6;
  inline bool has_tz() const;
  inline void clear_tz();
  static const int kTzFieldNumber = 6;
  inline ::google::protobuf::int32 tz() const;
  inline void set_tz(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:mrrocpp.edp.sensor.GenForceReading)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 fx_;
  ::google::protobuf::int32 fy_;
  ::google::protobuf::int32 fz_;
  ::google::protobuf::int32 tx_;
  ::google::protobuf::int32 ty_;
  ::google::protobuf::int32 tz_;
  friend void  protobuf_AddDesc_ati3084_2eproto();
  friend void protobuf_AssignDesc_ati3084_2eproto();
  friend void protobuf_ShutdownFile_ati3084_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static GenForceReading* default_instance_;
};
// -------------------------------------------------------------------

class SendBiasRequest : public ::google::protobuf::Message {
 public:
  SendBiasRequest();
  virtual ~SendBiasRequest();
  
  SendBiasRequest(const SendBiasRequest& from);
  
  inline SendBiasRequest& operator=(const SendBiasRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SendBiasRequest& default_instance();
  
  void Swap(SendBiasRequest* other);
  
  // implements Message ----------------------------------------------
  
  SendBiasRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SendBiasRequest& from);
  void MergeFrom(const SendBiasRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional bool dummy = 1;
  inline bool has_dummy() const;
  inline void clear_dummy();
  static const int kDummyFieldNumber = 1;
  inline bool dummy() const;
  inline void set_dummy(bool value);
  
  // @@protoc_insertion_point(class_scope:mrrocpp.edp.sensor.SendBiasRequest)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  bool dummy_;
  friend void  protobuf_AddDesc_ati3084_2eproto();
  friend void protobuf_AssignDesc_ati3084_2eproto();
  friend void protobuf_ShutdownFile_ati3084_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static SendBiasRequest* default_instance_;
};
// -------------------------------------------------------------------

class SendBiasReply : public ::google::protobuf::Message {
 public:
  SendBiasReply();
  virtual ~SendBiasReply();
  
  SendBiasReply(const SendBiasReply& from);
  
  inline SendBiasReply& operator=(const SendBiasReply& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SendBiasReply& default_instance();
  
  void Swap(SendBiasReply* other);
  
  // implements Message ----------------------------------------------
  
  SendBiasReply* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SendBiasReply& from);
  void MergeFrom(const SendBiasReply& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional bool dummy = 1;
  inline bool has_dummy() const;
  inline void clear_dummy();
  static const int kDummyFieldNumber = 1;
  inline bool dummy() const;
  inline void set_dummy(bool value);
  
  // @@protoc_insertion_point(class_scope:mrrocpp.edp.sensor.SendBiasReply)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  bool dummy_;
  friend void  protobuf_AddDesc_ati3084_2eproto();
  friend void protobuf_AssignDesc_ati3084_2eproto();
  friend void protobuf_ShutdownFile_ati3084_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static SendBiasReply* default_instance_;
};
// ===================================================================

class Ati3084_Stub;

class Ati3084 : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline Ati3084() {};
 public:
  virtual ~Ati3084();
  
  typedef Ati3084_Stub Stub;
  
  static const ::google::protobuf::ServiceDescriptor* descriptor();
  
  virtual void GetGenGForceReading(::google::protobuf::RpcController* controller,
                       const ::kiper::VoidMsg* request,
                       ::mrrocpp::edp::sensor::GenForceReading* response,
                       ::google::protobuf::Closure* done);
  virtual void SendBias(::google::protobuf::RpcController* controller,
                       const ::kiper::VoidMsg* request,
                       ::mrrocpp::edp::sensor::SendBiasReply* response,
                       ::google::protobuf::Closure* done);
  
  // implements Service ----------------------------------------------
  
  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(Ati3084);
};

class Ati3084_Stub : public Ati3084 {
 public:
  Ati3084_Stub(::google::protobuf::RpcChannel* channel);
  Ati3084_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~Ati3084_Stub();
  
  inline ::google::protobuf::RpcChannel* channel() { return channel_; }
  
  // implements Ati3084 ------------------------------------------
  
  void GetGenGForceReading(::google::protobuf::RpcController* controller,
                       const ::kiper::VoidMsg* request,
                       ::mrrocpp::edp::sensor::GenForceReading* response,
                       ::google::protobuf::Closure* done);
  void SendBias(::google::protobuf::RpcController* controller,
                       const ::kiper::VoidMsg* request,
                       ::mrrocpp::edp::sensor::SendBiasReply* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(Ati3084_Stub);
};


// ===================================================================


// ===================================================================

// GenForceReading

// required sint32 fx = 1;
inline bool GenForceReading::has_fx() const {
  return _has_bit(0);
}
inline void GenForceReading::clear_fx() {
  fx_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 GenForceReading::fx() const {
  return fx_;
}
inline void GenForceReading::set_fx(::google::protobuf::int32 value) {
  _set_bit(0);
  fx_ = value;
}

// required sint32 fy = 2;
inline bool GenForceReading::has_fy() const {
  return _has_bit(1);
}
inline void GenForceReading::clear_fy() {
  fy_ = 0;
  _clear_bit(1);
}
inline ::google::protobuf::int32 GenForceReading::fy() const {
  return fy_;
}
inline void GenForceReading::set_fy(::google::protobuf::int32 value) {
  _set_bit(1);
  fy_ = value;
}

// required sint32 fz = 3;
inline bool GenForceReading::has_fz() const {
  return _has_bit(2);
}
inline void GenForceReading::clear_fz() {
  fz_ = 0;
  _clear_bit(2);
}
inline ::google::protobuf::int32 GenForceReading::fz() const {
  return fz_;
}
inline void GenForceReading::set_fz(::google::protobuf::int32 value) {
  _set_bit(2);
  fz_ = value;
}

// required sint32 tx = 4;
inline bool GenForceReading::has_tx() const {
  return _has_bit(3);
}
inline void GenForceReading::clear_tx() {
  tx_ = 0;
  _clear_bit(3);
}
inline ::google::protobuf::int32 GenForceReading::tx() const {
  return tx_;
}
inline void GenForceReading::set_tx(::google::protobuf::int32 value) {
  _set_bit(3);
  tx_ = value;
}

// required sint32 ty = 5;
inline bool GenForceReading::has_ty() const {
  return _has_bit(4);
}
inline void GenForceReading::clear_ty() {
  ty_ = 0;
  _clear_bit(4);
}
inline ::google::protobuf::int32 GenForceReading::ty() const {
  return ty_;
}
inline void GenForceReading::set_ty(::google::protobuf::int32 value) {
  _set_bit(4);
  ty_ = value;
}

// required sint32 tz = 6;
inline bool GenForceReading::has_tz() const {
  return _has_bit(5);
}
inline void GenForceReading::clear_tz() {
  tz_ = 0;
  _clear_bit(5);
}
inline ::google::protobuf::int32 GenForceReading::tz() const {
  return tz_;
}
inline void GenForceReading::set_tz(::google::protobuf::int32 value) {
  _set_bit(5);
  tz_ = value;
}

// -------------------------------------------------------------------

// SendBiasRequest

// optional bool dummy = 1;
inline bool SendBiasRequest::has_dummy() const {
  return _has_bit(0);
}
inline void SendBiasRequest::clear_dummy() {
  dummy_ = false;
  _clear_bit(0);
}
inline bool SendBiasRequest::dummy() const {
  return dummy_;
}
inline void SendBiasRequest::set_dummy(bool value) {
  _set_bit(0);
  dummy_ = value;
}

// -------------------------------------------------------------------

// SendBiasReply

// optional bool dummy = 1;
inline bool SendBiasReply::has_dummy() const {
  return _has_bit(0);
}
inline void SendBiasReply::clear_dummy() {
  dummy_ = false;
  _clear_bit(0);
}
inline bool SendBiasReply::dummy() const {
  return dummy_;
}
inline void SendBiasReply::set_dummy(bool value) {
  _set_bit(0);
  dummy_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace sensor
}  // namespace edp
}  // namespace mrrocpp

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ati3084_2eproto__INCLUDED
